dgp/contribs/pd/metadata.proto, dgp/contribs/pd/metadata_pb2.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/2)
=> - Add support for batch_id and version fields in pd scene metadata

dgp/datasets/annotations.py, dgp/datasets/synchronized_dataset.py, dgp/utils/ontology.py, dgp/utils/visualization.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/4)
=> Adding support for 2D instance and semseg annotations

dgp/contribs/pd/metadata.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/3)
=> - Add additional fields to PD metadata for easier scene splits

dgp/contribs/pd/metadata.proto, dgp/contribs/pd/metadata_pb2.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/5)
=> PD Metadata Fix

dgp/utils/visualization.py
A testing branch with scripts to use the visualization can be found here:https://github.com/jieli352/dgp/tree/test_instance_mask
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/6)
=> add instance visualization functionality.

dgp/contribs/pd/metadata.proto, dgp/contribs/pd/metadata_pb2.py
- Add support for MICHIGAN region_type to ParallelDomainSceneMetadata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/7)
=> [PD Metadata]

.githooks/pre-commit, .github/workflows/build-docker.yml, .github/workflows/pre-merge.yml, Makefile, README.md, dgp/README.md, dgp/annotations/base_annotation.py, dgp/annotations/bounding_box_2d_annotation.py, dgp/utils/testing.py, dgp/utils/torch_extension/pose.py, dgp/utils/torch_extension/stn.py, docs/AWS.md, docs/CONTRIBUTING.md, docs/GETTING_STARTED.md, docs/VIRTUAL_ENV.md, requirements.txt
- add pre-merge tests to github action
- add formatting, linting, commitlint checks
- fix linting errors
- update readme
- update yapf to 0.31.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/21)
=> ci: add pre-merge github action workflow

.github/workflows/build-docker.yml, .github/workflows/pre-merge.yml, README.md, docs/GETTING_STARTED.md
- pin jobs to release versions
- set login-action user to github.actor
- tigger build-docker when creating tags
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/22)
=> ci: update build-docker workflow

.github/workflows/doc-gen.yml, README.md, docs/Makefile, docs/README.md, docs/make.bat, docs/source/conf.py, docs/source/dgp.annotations.rst, docs/source/dgp.contribs.pd.rst, docs/source/dgp.contribs.rst, docs/source/dgp.datasets.rst, docs/source/dgp.proto.rst, docs/source/dgp.rst, docs/source/dgp.scripts.rst, docs/source/dgp.utils.cloud.rst, docs/source/dgp.utils.rst, docs/source/dgp.utils.structures.rst, docs/source/dgp.utils.torch_extension.rst, docs/source/index.rst, docs/source/modules.rst, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/44)
=> docs: rhino and sphinx integration

.github/workflows/doc-gen.yml, docs/source/conf.py, docs/source/dgp.rst
Fix spacing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/54)
=> docs: update documentation workflow to support config files

.github/workflows/coverage.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/58)
=> ci: fix admin access for coverage workflow

.github/workflows/coverage.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/62)
=> ci: allow coverage flow to run on pull requests

.githooks/pre-commit, .github/workflows/coverage.yml, README.md, docs/CONTRIBUTING.md
- update README.md and CONTRIBUTING.md
- update code coverage threshold to 39
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/60)
=> docs: update homepage and contributing.md

dgp/datasets/pd_dataset.py, dgp/datasets/synchronized_dataset.py
This exposes dataset_root and accumulation arguments for the pd dataset classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/72)
=> feat: update pd_dataset api

.github/workflows/pre-merge.yml, dgp/datasets/base_dataset.py, dgp/utils/testing.py, requirements.txt, tests/test_datasets_timeout.py
- remove unused variable annotation_index
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/73)
=> fix: speed up base dataset init

docs/requirements-doc.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/75)
=> docs: temporary fix for mistune error

dgp/proto/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/66)
=> docs: update proto readme

.github/workflows/coverage.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/77)
=> test: increase test coverage thresh to 46

dgp/__init__.py, dgp/agents/__init__.py, dgp/agents/agent_2d.py, dgp/agents/agent_3d.py, dgp/agents/base_agent.py, dgp/constants.py, dgp/datasets/agent_dataset.py, dgp/datasets/base_dataset.py, dgp/datasets/frame_dataset.py, dgp/features/__init__.py, dgp/features/feature_ontology.py, dgp/utils/protobuf.py, dgp/utils/structures/bounding_box_3d.py, tests/data/dgp/test_scene/agents_pcc_mini_v1.json, tests/data/dgp/test_scene/scene_01/agent/agent_tracks_7d48300052566e2843254f26090898f3d741d14f.json, tests/data/dgp/test_scene/scene_01/agent/agents_slices_e6511f8f1f4b52e677640df3c19d277b05fd48ad.json, tests/data/dgp/test_scene/scene_01/agents_238ba18d1c9db1c73589e52dda56fcca6f60b2eb.json, tests/data/dgp/test_scene/scene_01/feature_ontology/5db09fd03b2d9f74b7871c86d7c40cbaac85cc66.json, tests/data/dgp/test_scene/scene_02/agent/agent_tracks_95f7a4221d5de5b1de78bc1cea4022e6d000d807.json, tests/data/dgp/test_scene/scene_02/agent/agents_slices_d2b496390be1e50fa6774d10c5dc0c82eebb7a7f.json, tests/data/dgp/test_scene/scene_02/agents_66362c1248ba9eb1b94f650913f6f6782923706a.json, tests/data/dgp/test_scene/scene_02/feature_ontology/5db09fd03b2d9f74b7871c86d7c40cbaac85cc66.json, tests/test_agent_dataset.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/67)
=> feat: add agent class and support (depends on schema PR)

dgp/__init__.py
- use pwd as default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/79)
=> fix: fix bug due to empty env

dgp/__init__.py, dgp/proto/annotations.proto, dgp/proto/annotations_pb2.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/83)
=> schema: add classification annotation type

dgp/utils/dataset_conversion.py
-  Use with Pool() to close multiprocess in compute_image_statistics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/82)
=> fix: fix bug in multiprocessing pool

dgp/proto/annotations.proto, dgp/proto/annotations_pb2.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/84)
=> schema: add attribute field to ClassificationAnnotation message

.github/workflows/coverage.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/89)
=> ci: increase test coverage thresh to 49

dgp/__init__.py, dgp/annotations/depth_annotation.py, dgp/datasets/base_dataset.py, dgp/datasets/synchronized_dataset.py, dgp/proto/README.md, tests/test_autolabel_dataset.py
This adds the ability to load autolabel scenes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/80)
=> feat: add ability to load autolabels

dgp/datasets/base_dataset.py, dgp/datasets/pd_dataset.py, tests/test_autolabel_dataset.py
* Fixes a bug in autolabel test masked by use_diskcache defaulting to true
* Exposes autolabel root for PD scenes
* Additional tweaks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/92)
=> fix: slight change to autolabels and support for pd

dgp/utils/dataset_conversion.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/97)
=> fix: Add option to specify num_processes in compute_image_statistics

.github/workflows/build-docker.yml, .github/workflows/coverage.yml, .github/workflows/doc-gen.yml, .github/workflows/pre-merge.yml, .pre-commit-config.yaml, Dockerfile, requirements.txt
Bringing this repo up to speed with the rest of the ecosystem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/125)
=> ci: updating packages to downstream, including Ubuntu20 and py39

dgp/utils/dataset_conversion.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/131)
=> fix: bug in valid_extensions in compute_image_statistics method

dgp/contribs/dgp2wicker/README.md, dgp/contribs/dgp2wicker/dgp2wicker/dataset.py, dgp/contribs/dgp2wicker/dgp2wicker/ingest.py, dgp/contribs/dgp2wicker/dgp2wicker/serializers.py
This adds support for radar protos in dgp2wicker. It was tested by converting a small internal dataset.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/140)
=> feat: add radar to dgp2wicker

.pre-commit-config.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/148)
=> ci: fix broken pre-merge test

.pre-commit-config.yaml, dgp/proto/annotations.proto, dgp/proto/annotations_pb2.py, dgp/proto/point_cloud.proto, dgp/proto/point_cloud_pb2.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/143)
=> schema: add instance and semantic segmentation 3D schema

requirements.txt
@chrisochoatri I have updated the versioning. Please tell me if it you have any other concerns
=> build: relax dependency versioning for protobuf

dgp/proto/annotations.proto, dgp/proto/annotations_pb2.py
This change is [<img src="https://reviewable.tri-ad.tech/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/152)
=> schema: modify segmentation 3d schema with point_index

dgp/utils/dataset_conversion.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/155)
=> chore: support .dat rgb file extension

Dockerfile, docs/requirements-doc.txt
Updates docker base image to resolve build failure.
Also updates sphinx version to pass ci.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/159)
=> fix: update base docker

dgp/contribs/dgp2wicker/requirements.txt, dgp/contribs/dgp2wicker/sample_wickerconfig.json
Updates dgp2wicker to latest wicker, adds some missing requirements and new expected configuration fields.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/160)
=> feat: update dgp2wicker for latest wicker
