TRI-ML/dgp

.github/workflows/doc-gen.yml

- fix typo `main` -> `master`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/46)

ci: trigger doc-gen workflow on master branch

---

.github/workflows/coverage.yml

test: fix badge generation bug
We  manually add in the aut-commentor, since the remote git is not set to populate it by itself
Example: https://github.com/sshusainTRI/dgp/commit/46d41ffc3f839fe3e3419d16d85afe8394ba0e85
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/56)

test: fix badge generation bug

---

dgp/datasets/base_dataset.py

This adds a deterministic option for the scene cache which prevents some errors when using spawn instead of fork for multiprocessing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/68)

feat: restore deterministic scene cache environment var

---

dgp/datasets/frame_dataset.py
dgp/datasets/pd_dataset.py
dgp/datasets/synchronized_dataset.py
dgp/utils/colors.py

- This allows users to specify if they want to use the scene disk cache when memory is not a concern. 
- Also adds some minor format changes and silences a pylint warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/74)

feat: expose disk cache setting to synchronized and pd datasets

---

requirements.txt

`matplotlib` 3.0.1, currently required in `requirements.txt`, is not compatible with Python 3.8 which is the default python version for Ubuntu 20.0. Attempting installation will use the `platform` module and expect it has `linux_distribution`, but this has been moved to the `distro` module in modern Python.
I encountered this issue when installing DGP [in a venv](https://github.com/TRI-ML/dgp/blob/master/docs/VIRTUAL_ENV.md). Our framework in Woven uses Python 3.8.
Assuming Matplotlib respects semantic versioning, I expect these relaxed version requirements won't be a problem, but we ought to only allow different minor and patch versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

fix: allow end-uers to use more modern version of matplotlib dep

---

Dockerfile

This adds a temporary fix to the dockerfile to add the new nvidia gpg key. See [here](https://forums.developer.nvidia.com/t/gpg-error-http-developer-download-nvidia-com-compute-cuda-repos-ubuntu1804-x86-64/212904) for more details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/91)

fix: update nvidia gpg key

---

dgp/proto/geometry.proto
dgp/proto/geometry_pb2.py

This updates the camera intrinsics proto to include the changes made by PD: https://github.com/parallel-domain/dgp/blob/master/dgp/proto/geometry.proto#L30 
But also adds support for other camera distortion models such as the double sphere model.
Additional PRs will be needed for the dataloaders to use this information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/86)

schema: add support for additional camera models in camera intrinsics

---

.github/workflows/coverage.yml
.github/workflows/doc-gen.yml
.github/workflows/pre-merge.yml
Dockerfile
requirements-dev.txt
requirements.txt
setup.py

This commit splits requirements into dependencies for lib and ones for dev. It allows an external repository that would import dgp to install not all the dependencies but only lib dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/96)

build: split requirements into lib and dev

---

docs/CONTRIBUTING.md

Clarify an important workflow in `CONTRIBUTING.md` to avoid users adding compiled protos through their own workflows.
Example: related [PR](https://github.com/TRI-ML/dgp/pull/102) with above issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/103)

docs: add instructions for protos contribution

---

Dockerfile

11.1-devel-ubuntu18.04 is no longer available, so we use 11.1.1-devel-ubuntu18.04 in our Dockerfile.
This addresses #106 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/107)

fix: fix base image name in Dockerfile

---

Dockerfile

This addresses #105 . For Ubuntu 18, default python is 2.7 and python3 is 3.x, so we need to symlink `python3` and not `python`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/108)

fix: symlink python3, not python, to python3.7

---

.pylintrc

This is toward unblocking #101 which is stuck on a pylint configuration issue. We provide some configuration in `.pylintrc` that seems to expect the `check_docs` plugin, but the new plugin is `docparams`. We therefore explicitly load the `docparams` plugin when running pylint.
Before this change, run
```
pylint setup.py
```
in the root of the repo, and you'll see
```
root@hostname:/home/dgp# pylint setup.py
************* Module /home/dgp/.pylintrc
.pylintrc:1: [E0015(unrecognized-option), ] Unrecognized option found: accept-no-param-doc, accept-no-return-doc, accept-no-yields-doc
```
After this change, the above example runs without errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

fix: explicitly load docparams pylint plugin in .pylintrc

---

dgp/proto/annotations.proto
dgp/proto/annotations_pb2.py

- add 3D equivalents in Cartesian coordinates in sensor space for KeyPoint2D,
KeyLine2D and Polygon2D on the image plane respectively.
This PR is based on Nisse's PR https://github.com/TRI-ML/dgp/pull/45
I don't have write access to the aformentioned PR so I opened a new PR with the changes asked by Quincy, after clarifications from Nisse.
Sorry for the incovenience @tk-woven ; let's continue discussion on this  PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/101)

schema: add KeyPoint3D, KeyLine3D, Polygon3D

---

docs/VIRTUAL_ENV.md

The virtual environment expects people can run `make test` without installing pytest.
This PR fixes issue https://github.com/TRI-ML/dgp/issues/104
Before this fix
```
copying dgp/utils/torch_extension/stn.py -> build/lib/dgp/utils/torch_extension
running egg_info
creating dgp.egg-info
writing dgp.egg-info/PKG-INFO
writing dependency_links to dgp.egg-info/dependency_links.txt
writing entry points to dgp.egg-info/entry_points.txt
writing requirements to dgp.egg-info/requires.txt
writing top-level names to dgp.egg-info/top_level.txt
writing manifest file 'dgp.egg-info/SOURCES.txt'
reading manifest file 'dgp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.proto' found under directory '*'
writing manifest file …
```

fix: virtual environment to be able to run make test

---

docs/README.md
docs/requirements-doc.txt

In an attempt to address a CVE (CVE-2022-34749) for one of our docs dependencies, `mistune`, I found multiple issues. The first is that we cannot address the CVE until some Sphinx API issues are solved in upstream Sphinx. The second issue is that our docs building is broken, presumably by the update to Python 3.7 as some regexs from `rinohtype` were failing to compile. This work fixes the docs build and also updates the documentation for completeness.
`m2r2`, which requires `mistune`, was having us install the _newer_ version of `mistune` that breaks against the Sphinx API, so we have to update `m2r2` to use a version that pins against the older `mistune`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

fix: fix documentation build and docs

---

.github/workflows/pre-merge.yml
.pre-commit-config.yaml

This is toward #114 . This moves more linting from SuperLinter to pre-commit. In particular, it moves
- check-json
- gitleaks
- htmlhint
- shellcheck
- shfmt
For `gitleaks`, we have to use a Docker-wrapped hook ID to avoid having our end-users manually install the `gitleaks` tool themselves. Also, SuperLinter suggests that it runs `shfmt` but is not entirely clear about it (since its configuration is for `shellcheck`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/122)

feat: move more linters from SuperLinter to pre-commit

---

.github/workflows/pre-merge.yml
.pre-commit-config.yaml
README.md
dgp/README.md
dgp/proto/README.md
docs/AWS.md
docs/CONTRIBUTING.md
docs/GETTING_STARTED.md
docs/README.md
docs/VIRTUAL_ENV.md

This is toward #114 . SuperLinter uses `markdownlint` for linting Markdown. When running the latest version on DGP, I found many violations. Instead of manually requiring conformance to specific style, I replace `markdownlint` with `prettier` which will auto-format Markdown files for us.
I've also disabled the natural language validator since there is no corresponding pre-commit hook for it. I don't think this validator is critical. What's more important is that we enforce clear meaning in prose in code review.
Lastly, I've built the docs locally and glanced over them (rather quickly). Everything seems to be okay still, including the PDF generated by `rinoh`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

feat: replace markdownlint with `prettier` Markdown auto-formatting

---

dgp/annotations/camera_transforms.py
tests/test_camera_transforms.py

This adds additional transformations for working with camera datums and transforming (most) annotations in a consistent manner. This simplifies lots of data pre-processing and augmentation work by consuming datums formatted as the output of a SychronizedScene, and returning new datums.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/126)

feat: add camera datum augmentations

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

This introduces issue templates for GitHub issues. Issue templates present issue creators with options between different pre-populated issue bodies. See FAIR's [Detectron2 New-Issues](https://github.com/facebookresearch/detectron2/issues/new/choose) for an example.
This also adds a number of default assignees. The default assignees are not required to solve the issues themselves, but they are added so that at least someone gets a notification when a new issue is opened. This way we can triage or re-assign as needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/127)

feat: add GitHub issue templates with default assignees

---

docs/source/conf.py

In order to resolve #116, I propose to use `git describe`.  
In future, I will fold past major release into the single doc as other popular projects do.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/128)

docs: remove version-hardcofing from Sphinx

---

.github/workflows/doc-gen.yml

* As shown in [this run](https://github.com/TRI-ML/dgp/actions/runs/3050002270),  "PR #128" causes a build break
* I confirmed `actions/checkout` in "doc-gen" does only a shallow clone, which fetch no `git tag`
- Change `actions/checkout` to the deep clone in "doc-gen" 
- Not to repeat this stupid mistake, I propose to trigger "doc-gen" also at pre-merge (i.e. `on.pull_request`)
- However, to avoid messy `git push` in GH pages, I introduce a skip condition depending on  `github.ref `
* Fold per-tag Sphinx docs into the single GH pages like other projects
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/129)

fix: do the deep clone in a GH action, "doc-gen"

---

dgp/utils/dataset_conversion.py

Some ML teams are handling image data with uppercase extensions such as `.JPG`, `.PNG`.
If there are no negative effects, I would like to support such uppercase extensions in `compute_image_statistics` method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/130)

fix: supported extensions in compute_image_statistics method

---

dgp/annotations/camera_transforms.py
dgp/annotations/transforms.py
dgp/contribs/dgp2wicker/.dockerignore
dgp/contribs/dgp2wicker/Dockerfile
dgp/contribs/dgp2wicker/Makefile
dgp/contribs/dgp2wicker/README.md
dgp/contribs/dgp2wicker/dgp2wicker/__init__.py
dgp/contribs/dgp2wicker/dgp2wicker/cli.py
dgp/contribs/dgp2wicker/dgp2wicker/dataset.py
dgp/contribs/dgp2wicker/dgp2wicker/ingest.py
dgp/contribs/dgp2wicker/dgp2wicker/serializers.py
dgp/contribs/dgp2wicker/readme.md
dgp/contribs/dgp2wicker/requirements.txt
dgp/contribs/dgp2wicker/sample_wickerconfig.json
dgp/contribs/dgp2wicker/setup.py
dgp/contribs/dgp2wicker/tests/__init__.py
dgp/contribs/dgp2wicker/tests/test.py

This adds a semi standalone docker for saving DGP Synchronized Scene output in Wicker.
This is tested primarily manually due to the need for s3 access. Please build the docker, pass s3 credentials, and run test.py for more details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/132)

feat: add dgp2wicker conversion

---

dgp/contribs/dgp2wicker/dgp2wicker/dataset.py

Fixes a small error in dgp2wicker base dataset. Depth is the only annotation type that does not have an ontology.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/133)

fix: fixed depth in dgp2wicker

---

dgp/contribs/dgp2wicker/dgp2wicker/cli.py
dgp/contribs/dgp2wicker/dgp2wicker/ingest.py

This adds support for syncing data from two locations when converting to wicker. A common use case is if the scene dataset json references a scene with just annotations or perhaps backfill for a missing datum (ex radar), and we also need to convert the raw data for this scene stored elsewhere.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/141)

feat: add alternate scene location for dgp2wicker

---

dgp/datasets/base_dataset.py
dgp/datasets/synchronized_dataset.py
tests/test_datasets.py

This adds a flag to base_dataset and synchronized scene to optionally skip loading the raw image data in a camera datum. The rgb key will contain a None value. The expected use case is when loading autolabels and the raw image data is not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/93)

feat: allow for loading image datums without rgb

---

dgp/annotations/__init__.py
dgp/annotations/bounding_box_2d_annotation.py
dgp/annotations/bounding_box_3d_annotation.py
dgp/annotations/camera_transforms.py
dgp/annotations/key_line_2d_annotation.py
dgp/annotations/key_line_3d_annotation.py
dgp/annotations/key_point_2d_annotation.py
dgp/annotations/key_point_3d_annotation.py
dgp/annotations/semantic_segmentation_2d_annotation.py
dgp/contribs/dgp2wicker/Makefile
dgp/contribs/dgp2wicker/dgp2wicker/ingest.py
dgp/contribs/dgp2wicker/dgp2wicker/serializers.py
dgp/datasets/base_dataset.py
dgp/utils/protobuf.py

- Adds support in dgp2wicker for key_point_2d, key_line_2d, key_point_3d, and key_line_3d
- Adds key_point_2d and key_line_3d support to SynchronizedScene 
- Fixes bug in dgp2wicker semantic segmentation 2d
- Removes duplicate code for most dgp2wicker serializers by switching open_pbobject to overloaded version parse_pbobject which can operate on bytes
- Skips unknown annotation types sometimes found in PD datasets in base_dataset
- Adds support for ontology V1 in dgp2wicker
- Fixes bug in dgp2wicker radar_point_cloud 2d annotation type handling
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/142)

feat: add key_point_2d/3d and key_line_2d/3d to dgp2wicker

---

requirements.txt

After installation, some missing dependency prevents the use of protobuf
```
Traceback (most recent call last):
File "/Users/chunleng.lim/Documents/git/dgp/test.py", line 1, in <module>
from dgp.annotations import semantic_segmentation_2d_annotation
File "/Users/chunleng.lim/Documents/git/dgp/dgp/annotations/__init__.py", line 5, in <module>
from dgp.annotations.ontology import (
File "/Users/chunleng.lim/Documents/git/dgp/dgp/annotations/ontology.py", line 7, in <module>
from dgp.proto.dataset_pb2 import Ontology as OntologyV1Pb2
File "/Users/chunleng.lim/Documents/git/dgp/dgp/proto/dataset_pb2.py", line 5, in <module>
from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google.protobuf'
```

build: fix missing protobuf dependency

---

dgp/datasets/base_dataset.py

Some parallel domain datasets are using (n,) for the point cloud shapes, this removes the implicit assumption that that all point cloud fields are (n,1).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/153)

fix: fix point cloud shape

---

docs/CONTRIBUTING.md

It seems that Makefile target `link-githooks` no longer exists and now it is called `setup-linters`
Update docs accordingly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/154)

docs: fix contributing guidelines

---

dgp/utils/protobuf.py

removes root logger from protobuf and lowers level to debug to silence ontology loading messages
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/158)

feat: switch logger to non-root logger in protobuf

---

Dockerfile
Makefile
docs/VIRTUAL_ENV.md
requirements.txt
setup.py

* upgrades the minimum version of numpy
* updates minimum xarray (pinned version was not compatible with numpy 1.20.3)
* uses a newer cython for building
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/161)

requirements: upgrade numpy

---

requirements.txt

Switches from Pillow to Pillow-simd in requirements.
Pillow-simd was being used in the docker but Pillow was listed in the reqs. The docker version is installed with avx2 support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/162)

build: switch to pillow simd by default

---

dgp/annotations/camera_transforms.py
requirements.txt
tests/test_camera_transforms.py

new image height was being calculated incorrectly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/164)

fix: fix bug in camera transform

---

dgp/annotations/camera_transforms.py

Feat: Add crop_top_only boolean flag to control the image crop area.

Feat: Add crop_top_only boolean flag to control the image crop area.

---

dgp/utils/structures/key_line_3d.py
dgp/utils/structures/key_point_3d.py
tests/annotation/test_key_line_3d_annotation.py

Keypoint and keyline 3d were being converted to integers on saving, the proto definition expects floats. This leads to loss of precision on saving.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TRI-ML/dgp/167)

fix: fix conversion in key point and keyline 3d

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

I am no longer working on anything related to DGP, and I never was a core designer or maintainer (only a maintainer to help unblock some Woven-internal things). So, I am removing myself as a default assignee on issue templates.

Remove tk-woven from default assignees
